### PR TITLE
updating elementary base image and runtime version

### PR DESCRIPTION
**Pull request by spanderman**
Runtime reached end of life, see raise issue:

https://github.com/flathub/com.github.louis77.tuner/issues/1

### CODE REVIEW

**Comment by spanderman** [comment]
Tested, application doesn't start. I am on Debian 11, flatpak version:

Flatpak 1.10.2

Running the app from terminal shows this critical error:

** (com.github.louis77.tuner:2): CRITICAL **: 12:35:45.712: Settings.vala:87: Could not connect: No such file or directory

** (com.github.louis77.tuner:2): CRITICAL **: 12:35:45.712: Settings.vala:107: Could not connect: No such file or directory

**Comment by louis77** [comment]
I'm wondering where this error is coming from, Tuner doesn't contain a `Settings.vala` file. 
I'll try reproduce it with a fresh Debian 11 install.

**Comment by louis77** [comment]
I found a similar issue here:
https://github.com/phase1geo/Minder/issues/364

Seems to be a problem with Granite library and elementary 6. I also found a fix for that:
https://github.com/phase1geo/Minder/commit/9a27fb76fdc8943b00b155d92032a76e8520cd2e

**Comment by spanderman** [comment]
Thanks @hfiguiere  and @louis77 !

**Pull request closed without merging**
