### PR TITLE
Bb

### PR DESCRIPTION
**Pull request by bztd**

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
@louis77 What are the source of these errors ?

```
** (com.github.louis77.tuner:2): CRITICAL **: 14:02:20.548: Settings.vala:87: Could not connect: No such file or directory

** (com.github.louis77.tuner:2): CRITICAL **: 14:02:20.548: Settings.vala:107: Could not connect: No such file or directory
```

**Comment by bztd** [comment]
With the above commit, the program works.

**Comment by bbhtt** [comment]
That patch doesn't look correct to me. I guess it'd prevent updating the app theme when system theme is changed or something like that ?

**Comment by bztd** [comment]
I haven't seen the function implemented, but I assume it's as you say. In the scenario where the suggested permission is granted and the patch is not applied, in my local tests the app does not adopt the system theme, nor the dark theme. So I don't see any relevance in leaving the lines in favor of the app's functionality.

**Pull request merged**
